### ISSUE TITLE
how did it go with this project?

### ISSUE THREAD

**Issue by GeoffreyEmery** [ricoud/nodebb-plugin-angtest#1]
Just curious if you were successful while doing this.

**Comment by ricoud** [comment]
I change my way. I decided to develop a nodejs site on a subdomain that used nodebb session. So I'm less dependent of nodebb evolution.

**Comment by GeoffreyEmery** [comment]
So you used  nodebb as a authentication provider and then built a new node app of that? Thats really interesting if so and what i was thinking about as well. 
  Did you have any issues with their API's in general?

**Comment by ricoud** [comment]
I write a small plugin that include every new customer in my node app database and used nodebb write api plugin and  nodebb-plugin-ns-api to retrieve nodebb information. Just one [issue](https://github.com/NicolasSiver/nodebb-plugin-ns-api/issues/1) with nodebb-plugin-ns-api.

**Comment by GeoffreyEmery** [comment]
Thanks
